runtime: java17
entrypoint: java -Dspring.profiles.active=cdg -Dbigquery.credentials.path=controle-de-gestion-361212-43410c6ca88a.json -jar aitm-server-0.1-SNAPSHOT.jar
instance_class: F2
env_variables:
  JAVA_OPTS: -Dtest # JAVA_OPTS or JAVA_USER_OPTS are ignored, this is why I have customized the entrypoint.
