export class AreaTable {
    readonly tableName: string = "area"
    readonly areUpdateDate: string = "are_update_date"
    readonly areBassinId: string = "are_bassin_id"
    readonly areBassinName: string = "are_bassin_name"
    readonly areLatitude: string = "are_latitude"
    readonly areLongitude: string = "are_longitude"
}
export class CategoryTable {
    readonly tableName: string = "category"
    readonly catUpdateDate: string = "cat_update_date"
    readonly catCategoryId: string = "cat_category_id"
    readonly catCategoryName: string = "cat_category_name"
    readonly catTopage: string = "cat_topage"
    readonly catCategoryType: string = "cat_category_type"
}
export class CompetitorCatchmentAreaTable {
    readonly tableName: string = "competitor_catchment_area"
    readonly ccaStoreId: string = "cca_store_id"
    readonly ccaCompetitorStoreId: string = "cca_competitor_store_id"
    readonly ccaRanking: string = "cca_ranking"
    readonly ccaAddedByPdv: string = "cca_added_by_pdv"
}
export class CompetitorPriceTable {
    readonly tableName: string = "competitor_price"
    readonly cpEan: string = "cp_ean"
    readonly cpStoreId: string = "cp_store_id"
    readonly cpStoreType: string = "cp_store_type"
    readonly cpVirtualPrice: string = "cp_virtual_price"
    readonly cpGrossPrice: string = "cp_gross_price"
    readonly cpNetPrice: string = "cp_net_price"
    readonly cpInDiscount: string = "cp_in_discount"
    readonly cpConsumerAdvantage: string = "cp_consumer_advantage"
    readonly cpStartDate: string = "cp_start_date"
    readonly cpEndDate: string = "cp_end_date"
}
export class CompetitorPriceWithMatchingTable {
    readonly tableName: string = "competitor_price_with_matching"
    readonly cpEan: string = "cp_ean"
    readonly cpStoreId: string = "cp_store_id"
    readonly cpStoreType: string = "cp_store_type"
    readonly cpVirtualPrice: string = "cp_virtual_price"
    readonly cpGrossPrice: string = "cp_gross_price"
    readonly cpNetPrice: string = "cp_net_price"
    readonly cpInDiscount: string = "cp_in_discount"
    readonly cpConsumerAdvantage: string = "cp_consumer_advantage"
    readonly cpStartDate: string = "cp_start_date"
    readonly cpEndDate: string = "cp_end_date"
}
export class CompetitorStoreTable {
    readonly tableName: string = "competitor_store"
    readonly csStoreId: string = "cs_store_id"
    readonly csStoreType: string = "cs_store_type"
    readonly csDriveType: string = "cs_drive_type"
    readonly csCompany: string = "cs_company"
    readonly csAddress1: string = "cs_address1"
    readonly csAddress2: string = "cs_address2"
    readonly csZipCode: string = "cs_zip_code"
    readonly csDepartmentNumber: string = "cs_department_number"
    readonly csCity: string = "cs_city"
    readonly csSquareFootage: string = "cs_square_footage"
    readonly csCircuit: string = "cs_circuit"
    readonly csRegionId: string = "cs_region_id"
    readonly csRegionLabel: string = "cs_region_label"
    readonly csAreaId: string = "cs_area_id"
    readonly csAreaLabel: string = "cs_area_label"
    readonly csActive: string = "cs_active"
}
export class CurrentSellingPricesTable {
    readonly tableName: string = "current_selling_prices"
    readonly curEan: string = "cur_ean"
    readonly curStoreId: string = "cur_store_id"
    readonly curTvaRate: string = "cur_tva_rate"
    readonly curSrpHt: string = "cur_srp_ht"
    readonly curSrpTtc: string = "cur_srp_ttc"
    readonly curFlagBpc: string = "cur_flag_bpc"
    readonly curAppliedPriceTtc: string = "cur_applied_price_ttc"
    readonly curCadencierPriceTtc: string = "cur_cadencier_price_ttc"
    readonly curCessionPrice: string = "cur_cession_price"
    readonly curVmm: string = "cur_vmm"
}
export class MatchingLinksTable {
    readonly tableName: string = "matching_links"
    readonly matCompany: string = "mat_company"
    readonly matCompetitorEan: string = "mat_competitor_ean"
    readonly matSelfEan: string = "mat_self_ean"
    readonly matMatchingType: string = "mat_matching_type"
    readonly matCoefficient: string = "mat_coefficient"
    readonly matCompetitorUnit: string = "mat_competitor_unit"
    readonly matCompetitorVolume: string = "mat_competitor_volume"
    readonly matSelfUnit: string = "mat_self_unit"
    readonly matSelfVolume: string = "mat_self_volume"
    readonly matIsActive: string = "mat_is_active"
    readonly matCreationDate: string = "mat_creation_date"
    readonly matUpdateDate: string = "mat_update_date"
}
export class NomenclatureTable {
    readonly tableName: string = "nomenclature"
    readonly nomFamilyId: string = "nom_family_id"
    readonly nomSubFamilyId: string = "nom_sub_family_id"
    readonly nomSegmentId: string = "nom_segment_id"
    readonly nomFamilyName: string = "nom_family_name"
    readonly nomSubFamilyName: string = "nom_sub_family_name"
    readonly nomSegmentName: string = "nom_segment_name"
    readonly nomUpdateDate: string = "nom_update_date"
}
export class ProductTable {
    readonly tableName: string = "product"
    readonly proEan: string = "pro_ean"
    readonly proIsReferent: string = "pro_is_referent"
    readonly proEanRef: string = "pro_ean_ref"
    readonly proName: string = "pro_name"
    readonly proBrand: string = "pro_brand"
    readonly proCategoryId: string = "pro_category_id"
    readonly proFamilyId: string = "pro_family_id"
    readonly proSubFamilyId: string = "pro_sub_family_id"
    readonly proSegmentId: string = "pro_segment_id"
    readonly proEga: string = "pro_ega"
    readonly proVolume: string = "pro_volume"
    readonly proBio: string = "pro_bio"
    readonly proPremarkedPrice: string = "pro_premarked_price"
    readonly proSeasonalProduct: string = "pro_seasonal_product"
    readonly proTypeMarque: string = "pro_type_marque"
    readonly proModeFabrication: string = "pro_mode_fabrication"
    readonly proCnuf: string = "pro_cnuf"
    readonly proTaxesExceptEga: string = "pro_taxes_except_ega"
    readonly proSign: string = "pro_sign"
}
export class RecommendationTable {
    readonly tableName: string = "recommendation"
    readonly recInitialPrice: string = "rec_initial_price"
    readonly recRecommendedPrice: string = "rec_recommended_price"
    readonly recFinalPrice: string = "rec_final_price"
    readonly aVRecommendedMargin: string = "AV_RecommendedMargin"
    readonly aVFinalMargin: string = "AV_FinalMargin"
    readonly aVPriceValidated: string = "AV_PriceValidated"
    readonly aVPriceValidationTime: string = "AV_PriceValidationTime"
    readonly aVPriceValidator: string = "AV_PriceValidator"
    readonly recPriceForced: string = "rec_price_forced"
    readonly recHasRuleBreach: string = "rec_has_rule_breach"
    readonly recHasRuleFailure: string = "rec_has_rule_failure"
    readonly recPriceChanged: string = "rec_price_changed"
    readonly recStrategyName: string = "rec_strategy_name"
    readonly recEan: string = "rec_ean"
    readonly recEanDependencyDepth: string = "rec_ean_dependency_depth"
    readonly recStoreId: string = "rec_store_id"
    readonly recProductTags: string = "rec_product_tags"
    readonly recProductTagFamilyLISTEROUGE: string = "rec_product_tag_family_LISTE_ROUGE"
    readonly recProductTagFamilySENSIBILITEMDDITM: string = "rec_product_tag_family_SENSIBILITE_MDD_ITM"
    readonly recProductTagFamilySENSIBILITEMDDNETTO: string = "rec_product_tag_family_SENSIBILITE_MDD_NETTO"
    readonly recProductTagFamilySENSIBILITEMNITM: string = "rec_product_tag_family_SENSIBILITE_MN_ITM"
    readonly recProductTagFamilySENSIBILITEMNNETTO: string = "rec_product_tag_family_SENSIBILITE_MN_NETTO"
    readonly recProductTagFamilySENSIBILITEPPITM: string = "rec_product_tag_family_SENSIBILITE_PP_ITM"
    readonly recLocationTags: string = "rec_location_tags"
    readonly recVariationControlBreach: string = "rec_variation_control_breach"
    readonly recConsistencyBreach: string = "rec_consistency_breach"
    readonly recBreachLowerLimitBreach: string = "rec_breach_lower_limit_breach"
    readonly recBreachLowerLimitFailure: string = "rec_breach_lower_limit_failure"
    readonly recLowerLimitBreach: string = "rec_lower_limit_breach"
    readonly recLowerLimitFailure: string = "rec_lower_limit_failure"
    readonly recUpperLimitBreach: string = "rec_upper_limit_breach"
    readonly recUpperLimitFailure: string = "rec_upper_limit_failure"
    readonly recCompetitorAlignmentBreach: string = "rec_competitor_alignment_breach"
    readonly recCompetitorAlignmentFailure: string = "rec_competitor_alignment_failure"
    readonly recBreachUpperLimitBreach: string = "rec_breach_upper_limit_breach"
    readonly recBreachUpperLimitFailure: string = "rec_breach_upper_limit_failure"
    readonly recSrpBreach: string = "rec_srp_breach"
    readonly recSrpFailure: string = "rec_srp_failure"
    readonly recInternalAlignmentMinBreach: string = "rec_internal_alignment_min_breach"
    readonly recInternalAlignmentMaxBreach: string = "rec_internal_alignment_max_breach"
    readonly aVPriceExportable: string = "AV_PriceExportable"
}
export class RecommendationWithSimulationTable {
    readonly tableName: string = "recommendation_with_simulation"
    readonly recInitialPrice: string = "rec_initial_price"
    readonly recRecommendedPrice: string = "rec_recommended_price"
    readonly recFinalPrice: string = "rec_final_price"
    readonly aVInitialMargin: string = "AV_InitialMargin"
    readonly aVRecommendedMargin: string = "AV_RecommendedMargin"
    readonly aVFinalMargin: string = "AV_FinalMargin"
    readonly aVPriceValidated: string = "AV_PriceValidated"
    readonly aVPriceValidationTime: string = "AV_PriceValidationTime"
    readonly aVPriceValidator: string = "AV_PriceValidator"
    readonly recPriceForced: string = "rec_price_forced"
    readonly recHasRuleBreach: string = "rec_has_rule_breach"
    readonly recHasRuleFailure: string = "rec_has_rule_failure"
    readonly recPriceChanged: string = "rec_price_changed"
    readonly recStrategyName: string = "rec_strategy_name"
    readonly recEan: string = "rec_ean"
    readonly recEanDependencyDepth: string = "rec_ean_dependency_depth"
    readonly recStoreId: string = "rec_store_id"
    readonly recProductTags: string = "rec_product_tags"
    readonly recProductTagFamilyLISTEROUGE: string = "rec_product_tag_family_LISTE_ROUGE"
    readonly recProductTagFamilySENSIBILITEMDDITM: string = "rec_product_tag_family_SENSIBILITE_MDD_ITM"
    readonly recProductTagFamilySENSIBILITEMDDNETTO: string = "rec_product_tag_family_SENSIBILITE_MDD_NETTO"
    readonly recProductTagFamilySENSIBILITEMNITM: string = "rec_product_tag_family_SENSIBILITE_MN_ITM"
    readonly recProductTagFamilySENSIBILITEMNNETTO: string = "rec_product_tag_family_SENSIBILITE_MN_NETTO"
    readonly recProductTagFamilySENSIBILITEPPITM: string = "rec_product_tag_family_SENSIBILITE_PP_ITM"
    readonly recLocationTags: string = "rec_location_tags"
    readonly recVariationControlBreach: string = "rec_variation_control_breach"
    readonly recConsistencyBreach: string = "rec_consistency_breach"
    readonly recBreachLowerLimitBreach: string = "rec_breach_lower_limit_breach"
    readonly recBreachLowerLimitFailure: string = "rec_breach_lower_limit_failure"
    readonly recLowerLimitBreach: string = "rec_lower_limit_breach"
    readonly recLowerLimitFailure: string = "rec_lower_limit_failure"
    readonly recUpperLimitBreach: string = "rec_upper_limit_breach"
    readonly recUpperLimitFailure: string = "rec_upper_limit_failure"
    readonly recCompetitorAlignmentBreach: string = "rec_competitor_alignment_breach"
    readonly recCompetitorAlignmentFailure: string = "rec_competitor_alignment_failure"
    readonly recBreachUpperLimitBreach: string = "rec_breach_upper_limit_breach"
    readonly recBreachUpperLimitFailure: string = "rec_breach_upper_limit_failure"
    readonly recSrpBreach: string = "rec_srp_breach"
    readonly recSrpFailure: string = "rec_srp_failure"
    readonly recInternalAlignmentMinBreach: string = "rec_internal_alignment_min_breach"
    readonly recInternalAlignmentMaxBreach: string = "rec_internal_alignment_max_breach"
    readonly aVPriceExportable: string = "AV_PriceExportable"
    readonly recSimulation: string = "rec_simulation"
}
export class RecommendationWithSimulation130MPricesTable {
    readonly tableName: string = "recommendation_with_simulation_130M_prices"
    readonly recInitialPrice: string = "rec_initial_price"
    readonly recRecommendedPrice: string = "rec_recommended_price"
    readonly recFinalPrice: string = "rec_final_price"
    readonly aVInitialMargin: string = "AV_InitialMargin"
    readonly aVRecommendedMargin: string = "AV_RecommendedMargin"
    readonly aVFinalMargin: string = "AV_FinalMargin"
    readonly aVPriceValidated: string = "AV_PriceValidated"
    readonly aVPriceValidationTime: string = "AV_PriceValidationTime"
    readonly aVPriceValidator: string = "AV_PriceValidator"
    readonly recPriceForced: string = "rec_price_forced"
    readonly recHasRuleBreach: string = "rec_has_rule_breach"
    readonly recHasRuleFailure: string = "rec_has_rule_failure"
    readonly recPriceChanged: string = "rec_price_changed"
    readonly recStrategyName: string = "rec_strategy_name"
    readonly recEan: string = "rec_ean"
    readonly recEanDependencyDepth: string = "rec_ean_dependency_depth"
    readonly recStoreId: string = "rec_store_id"
    readonly recProductTags: string = "rec_product_tags"
    readonly recProductTagFamilyLISTEROUGE: string = "rec_product_tag_family_LISTE_ROUGE"
    readonly recProductTagFamilySENSIBILITEMDDITM: string = "rec_product_tag_family_SENSIBILITE_MDD_ITM"
    readonly recProductTagFamilySENSIBILITEMDDNETTO: string = "rec_product_tag_family_SENSIBILITE_MDD_NETTO"
    readonly recProductTagFamilySENSIBILITEMNITM: string = "rec_product_tag_family_SENSIBILITE_MN_ITM"
    readonly recProductTagFamilySENSIBILITEMNNETTO: string = "rec_product_tag_family_SENSIBILITE_MN_NETTO"
    readonly recProductTagFamilySENSIBILITEPPITM: string = "rec_product_tag_family_SENSIBILITE_PP_ITM"
    readonly recLocationTags: string = "rec_location_tags"
    readonly recBreachLowerLimitBreach: string = "rec_breach_lower_limit_breach"
    readonly recBreachLowerLimitFailure: string = "rec_breach_lower_limit_failure"
    readonly recLowerLimitBreach: string = "rec_lower_limit_breach"
    readonly recLowerLimitFailure: string = "rec_lower_limit_failure"
    readonly recUpperLimitBreach: string = "rec_upper_limit_breach"
    readonly recUpperLimitFailure: string = "rec_upper_limit_failure"
    readonly recBreachUpperLimitBreach: string = "rec_breach_upper_limit_breach"
    readonly recBreachUpperLimitFailure: string = "rec_breach_upper_limit_failure"
    readonly recCompetitorAlignmentBreach: string = "rec_competitor_alignment_breach"
    readonly recCompetitorAlignmentFailure: string = "rec_competitor_alignment_failure"
    readonly recVariationControlBreach: string = "rec_variation_control_breach"
    readonly recConsistencyBreach: string = "rec_consistency_breach"
    readonly recSrpBreach: string = "rec_srp_breach"
    readonly recSrpFailure: string = "rec_srp_failure"
    readonly recInternalAlignmentMaxBreach: string = "rec_internal_alignment_max_breach"
    readonly recInternalAlignmentMinBreach: string = "rec_internal_alignment_min_breach"
    readonly recRankingAlignmentBreach: string = "rec_ranking_alignment_breach"
    readonly recRankingAlignmentFailure: string = "rec_ranking_alignment_failure"
    readonly recPromoBreach: string = "rec_promo_breach"
    readonly aVPriceExportable: string = "AV_PriceExportable"
    readonly recSimulation: string = "rec_simulation"
}
export class StoreTable {
    readonly tableName: string = "store"
    readonly stoStoreId: string = "sto_store_id"
    readonly stoName: string = "sto_name"
    readonly stoRegion: string = "sto_region"
    readonly stoLatitude: string = "sto_latitude"
    readonly stoLongitude: string = "sto_longitude"
    readonly stoOpen: string = "sto_open"
    readonly stoAddress: string = "sto_address"
    readonly stoCountry: string = "sto_country"
    readonly stoCity: string = "sto_city"
    readonly stoVocation: string = "sto_vocation"
    readonly stoModel: string = "sto_model"
    readonly stoSign: string = "sto_sign"
    readonly stoBassinId: string = "sto_bassin_id"
    readonly areUpdateDate: string = "are_update_date"
}
